//
//  UIColor+MMAdditions.h
//
//  Generated by Zeplin on 4/12/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (MMAdditions)

+ (UIColor *)mm_brightSkyBlueColor;
+ (UIColor *)mm_cafe0ColorColor;
+ (UIColor *)mm_orangeYellowColor;
+ (UIColor *)mm_shop2ColorColor;
+ (UIColor *)mm_etc4ColorColor;
+ (UIColor *)mm_place3ColorColor;
+ (UIColor *)mm_blackColor;
+ (UIColor *)mm_warmGreyColor;
+ (UIColor *)mm_paleGreyColor;
+ (UIColor *)mm_warmGreyTwoColor;
+ (UIColor *)mm_food1ColorColor;

@end
