//
//  UIColor+MMAdditions.h
//
//  Generated by Zeplin on 4/4/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (MMAdditions)

+ (UIColor *)mm_brightSkyBlueColor;
+ (UIColor *)mm_salmonColor;
+ (UIColor *)mm_orangeYellowColor;
+ (UIColor *)mm_easterPurpleColor;
+ (UIColor *)mm_periwinkleColor;
+ (UIColor *)mm_tealishColor;
+ (UIColor *)mm_blackColor;
+ (UIColor *)mm_warmGreyColor;
+ (UIColor *)mm_paleGreyColor;
+ (UIColor *)mm_warmGreyTwoColor;

@end
