//
//  UIColor+MMAdditions.m
//
//  Generated by Zeplin on 4/4/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+MMAdditions.h"

@implementation UIColor (MMAdditions)

+ (UIColor *)mm_brightSkyBlueColor {
	return [UIColor colorWithRed:0.0 green:181.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_salmonColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:107.0f / 255.0f blue:107.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_orangeYellowColor {
	return [UIColor colorWithRed:252.0f / 255.0f green:160.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)mm_easterPurpleColor {
	return [UIColor colorWithRed:188.0f / 255.0f green:127.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_periwinkleColor {
	return [UIColor colorWithRed:118.0f / 255.0f green:124.0f / 255.0f blue:254.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_tealishColor {
	return [UIColor colorWithRed:45.0f / 255.0f green:204.0f / 255.0f blue:178.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_blackColor {
	return [UIColor colorWithWhite:34.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_warmGreyColor {
	return [UIColor colorWithWhite:136.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_paleGreyColor {
	return [UIColor colorWithRed:227.0f / 255.0f green:227.0f / 255.0f blue:231.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)mm_warmGreyTwoColor {
	return [UIColor colorWithWhite:140.0f / 255.0f alpha:1.0f];
}

@end
