//
//  UIFont+MMAdditions.m
//
//  Generated by Zeplin on 4/4/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+MMAdditions.h"

@implementation UIFont (MMAdditions)

+ (UIFont *)mm_pinNameFont {
	return [UIFont fontWithName:@".AppleSDGothicNeoI-Medium" size:36.0f];
}

+ (UIFont *)mm_placeholderFont {
	return [UIFont fontWithName:@".AppleSDGothicNeoI-Regular" size:26.0f];
}

+ (UIFont *)mm_editorTitleFont {
	return [UIFont fontWithName:@".AppleSDGothicNeoI-Light" size:20.0f];
}

+ (UIFont *)mm_userNameFont {
	return [UIFont fontWithName:@".AppleSDGothicNeoI-Medium" size:18.0f];
}

+ (UIFont *)mm_textInputPlaceholder16PtFont {
	return [UIFont fontWithName:@"Avenir-Book" size:16.0f];
}

+ (UIFont *)mm_pinAddressFont {
	return [UIFont fontWithName:@".AppleSDGothicNeoI-Light" size:14.0f];
}

@end

//------ 폰트 정리 ------------
/*

핀뷰 
타이틀 36pt / regula / 00b5ff /
핀명 30pt / regula / 222222
핀주소 14pt / regula / 888888
에디터 제목 20pt / regula / 222222
placeholder 26pt / regula / e3e3e7
user name 18pt / regula / 222222
 
 
 
 
 
 
 
 
 
 
*/

