//
//  UIFont+MMAdditions.h
//
//  Generated by Zeplin on 4/4/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (MMAdditions)

+ (UIFont *)mm_pinNameFont;
+ (UIFont *)mm_placeholderFont;
+ (UIFont *)mm_editorTitleFont;
+ (UIFont *)mm_userNameFont;
+ (UIFont *)mm_textInputPlaceholder16PtFont;
+ (UIFont *)mm_pinAddressFont;

@end
