# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
    
target 'Momo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Momo
    # google map, places api
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    
    
    # facebook api
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage'

    pod 'JSONModel'
    pod 'SVProgressHUD'     # 로딩 팝업
    pod 'FontAwesomeKit/FontAwesome'    # icon fonts

end
