# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
    
target 'Momo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Momo
    pod 'GoogleMaps'
    pod 'SDWebImage'
    pod 'AFNetworking', '~> 3.0'



end
