source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

def shared_pods
    # Google
    # maps
    pod 'GoogleMaps’, '2.3'
    # analytics
    pod 'Google/Analytics'

    # Facebook api
    pod 'Bolts'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    # Realm Mobile DB
    pod 'Realm'
    
    # Networking
    pod 'AFNetworking', '~> 3.0'
    
    # UI
    pod 'SVProgressHUD'     # 로딩 팝업
end

target 'Momo' do
    shared_pods
end

target 'Momo_Realm' do
    shared_pods
end
